#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias ga='git add'
alias gc='git commit -m'
alias gp='git push'
alias avenv='source .venv/bin/activate'
alias grep='grep --color=auto'
alias l='ls --color=auto -CF'
alias hyconf='vim ~/.config/hypr/hyprland.conf'
alias hyreload='hyprctl reload'
alias open='thunar'
alias ml2='cd ~/Documents/oddity/ml2; avenv'
alias hybinds='cat ~/.config/hypr/hyprland.conf | grep exec,' # print keybinds
alias sh='TERM=xterm-256color ssh'
alias mount='sudo sshfs -o allow_other,default_permissions' # mnt fs (remote, local)
alias unmount='sudo umount -f' # unmount fs
PS1='[\u@\h \W]\$ '

eval "$(starship init bash)"
export PATH=$HOME/.local/bin:$PATH

