#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias ga='git add'
alias gc='git commit -m'
alias gp='git push'
alias avenv='source .venv/bin/activate'
alias grep='grep --color=auto'
alias l='ls --color=auto -CF'
alias hyconf='vim ~/.config/hypr/hyprland.conf'
alias hyreload='hyprctl reload'
alias open='thunar'
alias mount='sudo sshfs -o allow_other,default_permissions' # mnt fs (remote, local)
alias unmount='sudo umount -f' # unmount fs
PS1='[\u@\h \W]\$ '

eval "$(starship init bash)"
eval "$(direnv hook bash)"  # direnv eval hook
export PATH=$HOME/.local/bin:$PATH

export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"




